# // █▀▄ █▀▀ █▀▀ ▄▀█ █░█ █░░ ▀█▀
# // █▄▀ ██▄ █▀░ █▀█ █▄█ █▄▄ ░█░

$WORKFLOW_ICON=🏡
$WORKFLOW_DESCRIPTION = Home configuration

# External 27 inch (main) monitor on the left
monitor = HDMI-A-2, 1920x1080@60Hz, 0x0, 1

# External 22 inch aux monitor on the left of main monitor
monitor = DP-1, 1920x1080@60Hz, auto-center-left, 1

# Laptop monitor to the right, top edges aligned
monitor = eDP-1, 1920x1080@60Hz, auto-center-right, 1.875

workspace = 2, monitor:HDMI-A-2, default:true
workspace = 1, monitor:DP-1, default:true
workspace = name:stats, monitor:eDP-1, on-created-empty:kitty -e btop, default:true
